# fly.toml app configuration file generated for casterscan on 2025-08-26T15:51:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'casterscan'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  
  # Increase timeouts for SSE streams and gRPC connections
  [http_service.http_options.response]
    complete_timeout = "120s"
    
  [http_service.http_options.request]
    body_timeout = "120s"
    read_timeout = "120s"
    
  # HTTP/2 settings for gRPC compatibility
  [http_service.http_options.h2_backend]
    enabled = true

  # Health check
  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = 'production'
  PORT = '3000'

# Set your Neynar API key as a secret:
# fly secrets set NEYNAR_API_KEY=your-api-key-here
