/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareCastRouteImport } from './routes/share-cast'
import { Route as PingRouteImport } from './routes/ping'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernamesUsernameRouteImport } from './routes/usernames.$username'
import { Route as FidsFidRouteImport } from './routes/fids.$fid'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CastsHashRouteImport } from './routes/casts.$hash'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as DotwellKnownFarcasterDotjsonRouteImport } from './routes/[.]well-known/farcaster[.]json'
import { Route as ApiSnapchainInfoRouteImport } from './routes/api/snapchain/info'
import { Route as ApiSnapchainEventRouteImport } from './routes/api/snapchain/event'
import { Route as ApiSnapchainCastRouteImport } from './routes/api/snapchain/cast'
import { Route as ApiSignersStatsRouteImport } from './routes/api/signers/stats'
import { Route as ApiSignersMessagesRouteImport } from './routes/api/signers/messages'
import { Route as ApiSignersEnrichedRouteImport } from './routes/api/signers/enriched'
import { Route as ApiNeynarUserRouteImport } from './routes/api/neynar/user'
import { Route as ApiNeynarCastRouteImport } from './routes/api/neynar/cast'
import { Route as ApiFarcasterUserRouteImport } from './routes/api/farcaster/user'
import { Route as ApiFarcasterCastRouteImport } from './routes/api/farcaster/cast'
import { Route as ApiFidFidStatsRouteImport } from './routes/api/fid/$fid/stats'
import { Route as ApiFarcasterFidVerificationsRouteImport } from './routes/api/farcaster/$fid/verifications'
import { Route as ApiFarcasterFidSignersRouteImport } from './routes/api/farcaster/$fid/signers'
import { Route as ApiFarcasterFidReactionsRouteImport } from './routes/api/farcaster/$fid/reactions'
import { Route as ApiFarcasterFidLinksRouteImport } from './routes/api/farcaster/$fid/links'
import { Route as ApiFarcasterFidKeysRouteImport } from './routes/api/farcaster/$fid/keys'
import { Route as ApiFarcasterFidCastsRouteImport } from './routes/api/farcaster/$fid/casts'

const ShareCastRoute = ShareCastRouteImport.update({
  id: '/share-cast',
  path: '/share-cast',
  getParentRoute: () => rootRouteImport,
} as any)
const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernamesUsernameRoute = UsernamesUsernameRouteImport.update({
  id: '/usernames/$username',
  path: '/usernames/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const FidsFidRoute = FidsFidRouteImport.update({
  id: '/fids/$fid',
  path: '/fids/$fid',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CastsHashRoute = CastsHashRouteImport.update({
  id: '/casts/$hash',
  path: '/casts/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownFarcasterDotjsonRoute =
  DotwellKnownFarcasterDotjsonRouteImport.update({
    id: '/.well-known/farcaster.json',
    path: '/.well-known/farcaster.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSnapchainInfoRoute = ApiSnapchainInfoRouteImport.update({
  id: '/api/snapchain/info',
  path: '/api/snapchain/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapchainEventRoute = ApiSnapchainEventRouteImport.update({
  id: '/api/snapchain/event',
  path: '/api/snapchain/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapchainCastRoute = ApiSnapchainCastRouteImport.update({
  id: '/api/snapchain/cast',
  path: '/api/snapchain/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignersStatsRoute = ApiSignersStatsRouteImport.update({
  id: '/api/signers/stats',
  path: '/api/signers/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignersMessagesRoute = ApiSignersMessagesRouteImport.update({
  id: '/api/signers/messages',
  path: '/api/signers/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignersEnrichedRoute = ApiSignersEnrichedRouteImport.update({
  id: '/api/signers/enriched',
  path: '/api/signers/enriched',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNeynarUserRoute = ApiNeynarUserRouteImport.update({
  id: '/api/neynar/user',
  path: '/api/neynar/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNeynarCastRoute = ApiNeynarCastRouteImport.update({
  id: '/api/neynar/cast',
  path: '/api/neynar/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarcasterUserRoute = ApiFarcasterUserRouteImport.update({
  id: '/api/farcaster/user',
  path: '/api/farcaster/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarcasterCastRoute = ApiFarcasterCastRouteImport.update({
  id: '/api/farcaster/cast',
  path: '/api/farcaster/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFidFidStatsRoute = ApiFidFidStatsRouteImport.update({
  id: '/api/fid/$fid/stats',
  path: '/api/fid/$fid/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarcasterFidVerificationsRoute =
  ApiFarcasterFidVerificationsRouteImport.update({
    id: '/api/farcaster/$fid/verifications',
    path: '/api/farcaster/$fid/verifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFarcasterFidSignersRoute = ApiFarcasterFidSignersRouteImport.update({
  id: '/api/farcaster/$fid/signers',
  path: '/api/farcaster/$fid/signers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarcasterFidReactionsRoute =
  ApiFarcasterFidReactionsRouteImport.update({
    id: '/api/farcaster/$fid/reactions',
    path: '/api/farcaster/$fid/reactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFarcasterFidLinksRoute = ApiFarcasterFidLinksRouteImport.update({
  id: '/api/farcaster/$fid/links',
  path: '/api/farcaster/$fid/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarcasterFidKeysRoute = ApiFarcasterFidKeysRouteImport.update({
  id: '/api/farcaster/$fid/keys',
  path: '/api/farcaster/$fid/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarcasterFidCastsRoute = ApiFarcasterFidCastsRouteImport.update({
  id: '/api/farcaster/$fid/casts',
  path: '/api/farcaster/$fid/casts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/not-found': typeof NotFoundRoute
  '/ping': typeof PingRoute
  '/share-cast': typeof ShareCastRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/events': typeof ApiEventsRoute
  '/casts/$hash': typeof CastsHashRoute
  '/events/$id': typeof EventsIdRoute
  '/fids/$fid': typeof FidsFidRoute
  '/usernames/$username': typeof UsernamesUsernameRoute
  '/api/farcaster/cast': typeof ApiFarcasterCastRoute
  '/api/farcaster/user': typeof ApiFarcasterUserRoute
  '/api/neynar/cast': typeof ApiNeynarCastRoute
  '/api/neynar/user': typeof ApiNeynarUserRoute
  '/api/signers/enriched': typeof ApiSignersEnrichedRoute
  '/api/signers/messages': typeof ApiSignersMessagesRoute
  '/api/signers/stats': typeof ApiSignersStatsRoute
  '/api/snapchain/cast': typeof ApiSnapchainCastRoute
  '/api/snapchain/event': typeof ApiSnapchainEventRoute
  '/api/snapchain/info': typeof ApiSnapchainInfoRoute
  '/api/farcaster/$fid/casts': typeof ApiFarcasterFidCastsRoute
  '/api/farcaster/$fid/keys': typeof ApiFarcasterFidKeysRoute
  '/api/farcaster/$fid/links': typeof ApiFarcasterFidLinksRoute
  '/api/farcaster/$fid/reactions': typeof ApiFarcasterFidReactionsRoute
  '/api/farcaster/$fid/signers': typeof ApiFarcasterFidSignersRoute
  '/api/farcaster/$fid/verifications': typeof ApiFarcasterFidVerificationsRoute
  '/api/fid/$fid/stats': typeof ApiFidFidStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/not-found': typeof NotFoundRoute
  '/ping': typeof PingRoute
  '/share-cast': typeof ShareCastRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/events': typeof ApiEventsRoute
  '/casts/$hash': typeof CastsHashRoute
  '/events/$id': typeof EventsIdRoute
  '/fids/$fid': typeof FidsFidRoute
  '/usernames/$username': typeof UsernamesUsernameRoute
  '/api/farcaster/cast': typeof ApiFarcasterCastRoute
  '/api/farcaster/user': typeof ApiFarcasterUserRoute
  '/api/neynar/cast': typeof ApiNeynarCastRoute
  '/api/neynar/user': typeof ApiNeynarUserRoute
  '/api/signers/enriched': typeof ApiSignersEnrichedRoute
  '/api/signers/messages': typeof ApiSignersMessagesRoute
  '/api/signers/stats': typeof ApiSignersStatsRoute
  '/api/snapchain/cast': typeof ApiSnapchainCastRoute
  '/api/snapchain/event': typeof ApiSnapchainEventRoute
  '/api/snapchain/info': typeof ApiSnapchainInfoRoute
  '/api/farcaster/$fid/casts': typeof ApiFarcasterFidCastsRoute
  '/api/farcaster/$fid/keys': typeof ApiFarcasterFidKeysRoute
  '/api/farcaster/$fid/links': typeof ApiFarcasterFidLinksRoute
  '/api/farcaster/$fid/reactions': typeof ApiFarcasterFidReactionsRoute
  '/api/farcaster/$fid/signers': typeof ApiFarcasterFidSignersRoute
  '/api/farcaster/$fid/verifications': typeof ApiFarcasterFidVerificationsRoute
  '/api/fid/$fid/stats': typeof ApiFidFidStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/not-found': typeof NotFoundRoute
  '/ping': typeof PingRoute
  '/share-cast': typeof ShareCastRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/events': typeof ApiEventsRoute
  '/casts/$hash': typeof CastsHashRoute
  '/events/$id': typeof EventsIdRoute
  '/fids/$fid': typeof FidsFidRoute
  '/usernames/$username': typeof UsernamesUsernameRoute
  '/api/farcaster/cast': typeof ApiFarcasterCastRoute
  '/api/farcaster/user': typeof ApiFarcasterUserRoute
  '/api/neynar/cast': typeof ApiNeynarCastRoute
  '/api/neynar/user': typeof ApiNeynarUserRoute
  '/api/signers/enriched': typeof ApiSignersEnrichedRoute
  '/api/signers/messages': typeof ApiSignersMessagesRoute
  '/api/signers/stats': typeof ApiSignersStatsRoute
  '/api/snapchain/cast': typeof ApiSnapchainCastRoute
  '/api/snapchain/event': typeof ApiSnapchainEventRoute
  '/api/snapchain/info': typeof ApiSnapchainInfoRoute
  '/api/farcaster/$fid/casts': typeof ApiFarcasterFidCastsRoute
  '/api/farcaster/$fid/keys': typeof ApiFarcasterFidKeysRoute
  '/api/farcaster/$fid/links': typeof ApiFarcasterFidLinksRoute
  '/api/farcaster/$fid/reactions': typeof ApiFarcasterFidReactionsRoute
  '/api/farcaster/$fid/signers': typeof ApiFarcasterFidSignersRoute
  '/api/farcaster/$fid/verifications': typeof ApiFarcasterFidVerificationsRoute
  '/api/fid/$fid/stats': typeof ApiFidFidStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/not-found'
    | '/ping'
    | '/share-cast'
    | '/.well-known/farcaster.json'
    | '/api/events'
    | '/casts/$hash'
    | '/events/$id'
    | '/fids/$fid'
    | '/usernames/$username'
    | '/api/farcaster/cast'
    | '/api/farcaster/user'
    | '/api/neynar/cast'
    | '/api/neynar/user'
    | '/api/signers/enriched'
    | '/api/signers/messages'
    | '/api/signers/stats'
    | '/api/snapchain/cast'
    | '/api/snapchain/event'
    | '/api/snapchain/info'
    | '/api/farcaster/$fid/casts'
    | '/api/farcaster/$fid/keys'
    | '/api/farcaster/$fid/links'
    | '/api/farcaster/$fid/reactions'
    | '/api/farcaster/$fid/signers'
    | '/api/farcaster/$fid/verifications'
    | '/api/fid/$fid/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/not-found'
    | '/ping'
    | '/share-cast'
    | '/.well-known/farcaster.json'
    | '/api/events'
    | '/casts/$hash'
    | '/events/$id'
    | '/fids/$fid'
    | '/usernames/$username'
    | '/api/farcaster/cast'
    | '/api/farcaster/user'
    | '/api/neynar/cast'
    | '/api/neynar/user'
    | '/api/signers/enriched'
    | '/api/signers/messages'
    | '/api/signers/stats'
    | '/api/snapchain/cast'
    | '/api/snapchain/event'
    | '/api/snapchain/info'
    | '/api/farcaster/$fid/casts'
    | '/api/farcaster/$fid/keys'
    | '/api/farcaster/$fid/links'
    | '/api/farcaster/$fid/reactions'
    | '/api/farcaster/$fid/signers'
    | '/api/farcaster/$fid/verifications'
    | '/api/fid/$fid/stats'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/not-found'
    | '/ping'
    | '/share-cast'
    | '/.well-known/farcaster.json'
    | '/api/events'
    | '/casts/$hash'
    | '/events/$id'
    | '/fids/$fid'
    | '/usernames/$username'
    | '/api/farcaster/cast'
    | '/api/farcaster/user'
    | '/api/neynar/cast'
    | '/api/neynar/user'
    | '/api/signers/enriched'
    | '/api/signers/messages'
    | '/api/signers/stats'
    | '/api/snapchain/cast'
    | '/api/snapchain/event'
    | '/api/snapchain/info'
    | '/api/farcaster/$fid/casts'
    | '/api/farcaster/$fid/keys'
    | '/api/farcaster/$fid/links'
    | '/api/farcaster/$fid/reactions'
    | '/api/farcaster/$fid/signers'
    | '/api/farcaster/$fid/verifications'
    | '/api/fid/$fid/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  NotFoundRoute: typeof NotFoundRoute
  PingRoute: typeof PingRoute
  ShareCastRoute: typeof ShareCastRoute
  DotwellKnownFarcasterDotjsonRoute: typeof DotwellKnownFarcasterDotjsonRoute
  ApiEventsRoute: typeof ApiEventsRoute
  CastsHashRoute: typeof CastsHashRoute
  EventsIdRoute: typeof EventsIdRoute
  FidsFidRoute: typeof FidsFidRoute
  UsernamesUsernameRoute: typeof UsernamesUsernameRoute
  ApiFarcasterCastRoute: typeof ApiFarcasterCastRoute
  ApiFarcasterUserRoute: typeof ApiFarcasterUserRoute
  ApiNeynarCastRoute: typeof ApiNeynarCastRoute
  ApiNeynarUserRoute: typeof ApiNeynarUserRoute
  ApiSignersEnrichedRoute: typeof ApiSignersEnrichedRoute
  ApiSignersMessagesRoute: typeof ApiSignersMessagesRoute
  ApiSignersStatsRoute: typeof ApiSignersStatsRoute
  ApiSnapchainCastRoute: typeof ApiSnapchainCastRoute
  ApiSnapchainEventRoute: typeof ApiSnapchainEventRoute
  ApiSnapchainInfoRoute: typeof ApiSnapchainInfoRoute
  ApiFarcasterFidCastsRoute: typeof ApiFarcasterFidCastsRoute
  ApiFarcasterFidKeysRoute: typeof ApiFarcasterFidKeysRoute
  ApiFarcasterFidLinksRoute: typeof ApiFarcasterFidLinksRoute
  ApiFarcasterFidReactionsRoute: typeof ApiFarcasterFidReactionsRoute
  ApiFarcasterFidSignersRoute: typeof ApiFarcasterFidSignersRoute
  ApiFarcasterFidVerificationsRoute: typeof ApiFarcasterFidVerificationsRoute
  ApiFidFidStatsRoute: typeof ApiFidFidStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share-cast': {
      id: '/share-cast'
      path: '/share-cast'
      fullPath: '/share-cast'
      preLoaderRoute: typeof ShareCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usernames/$username': {
      id: '/usernames/$username'
      path: '/usernames/$username'
      fullPath: '/usernames/$username'
      preLoaderRoute: typeof UsernamesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fids/$fid': {
      id: '/fids/$fid'
      path: '/fids/$fid'
      fullPath: '/fids/$fid'
      preLoaderRoute: typeof FidsFidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casts/$hash': {
      id: '/casts/$hash'
      path: '/casts/$hash'
      fullPath: '/casts/$hash'
      preLoaderRoute: typeof CastsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/farcaster.json': {
      id: '/.well-known/farcaster.json'
      path: '/.well-known/farcaster.json'
      fullPath: '/.well-known/farcaster.json'
      preLoaderRoute: typeof DotwellKnownFarcasterDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapchain/info': {
      id: '/api/snapchain/info'
      path: '/api/snapchain/info'
      fullPath: '/api/snapchain/info'
      preLoaderRoute: typeof ApiSnapchainInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapchain/event': {
      id: '/api/snapchain/event'
      path: '/api/snapchain/event'
      fullPath: '/api/snapchain/event'
      preLoaderRoute: typeof ApiSnapchainEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapchain/cast': {
      id: '/api/snapchain/cast'
      path: '/api/snapchain/cast'
      fullPath: '/api/snapchain/cast'
      preLoaderRoute: typeof ApiSnapchainCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signers/stats': {
      id: '/api/signers/stats'
      path: '/api/signers/stats'
      fullPath: '/api/signers/stats'
      preLoaderRoute: typeof ApiSignersStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signers/messages': {
      id: '/api/signers/messages'
      path: '/api/signers/messages'
      fullPath: '/api/signers/messages'
      preLoaderRoute: typeof ApiSignersMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signers/enriched': {
      id: '/api/signers/enriched'
      path: '/api/signers/enriched'
      fullPath: '/api/signers/enriched'
      preLoaderRoute: typeof ApiSignersEnrichedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/neynar/user': {
      id: '/api/neynar/user'
      path: '/api/neynar/user'
      fullPath: '/api/neynar/user'
      preLoaderRoute: typeof ApiNeynarUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/neynar/cast': {
      id: '/api/neynar/cast'
      path: '/api/neynar/cast'
      fullPath: '/api/neynar/cast'
      preLoaderRoute: typeof ApiNeynarCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/user': {
      id: '/api/farcaster/user'
      path: '/api/farcaster/user'
      fullPath: '/api/farcaster/user'
      preLoaderRoute: typeof ApiFarcasterUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/cast': {
      id: '/api/farcaster/cast'
      path: '/api/farcaster/cast'
      fullPath: '/api/farcaster/cast'
      preLoaderRoute: typeof ApiFarcasterCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fid/$fid/stats': {
      id: '/api/fid/$fid/stats'
      path: '/api/fid/$fid/stats'
      fullPath: '/api/fid/$fid/stats'
      preLoaderRoute: typeof ApiFidFidStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/$fid/verifications': {
      id: '/api/farcaster/$fid/verifications'
      path: '/api/farcaster/$fid/verifications'
      fullPath: '/api/farcaster/$fid/verifications'
      preLoaderRoute: typeof ApiFarcasterFidVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/$fid/signers': {
      id: '/api/farcaster/$fid/signers'
      path: '/api/farcaster/$fid/signers'
      fullPath: '/api/farcaster/$fid/signers'
      preLoaderRoute: typeof ApiFarcasterFidSignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/$fid/reactions': {
      id: '/api/farcaster/$fid/reactions'
      path: '/api/farcaster/$fid/reactions'
      fullPath: '/api/farcaster/$fid/reactions'
      preLoaderRoute: typeof ApiFarcasterFidReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/$fid/links': {
      id: '/api/farcaster/$fid/links'
      path: '/api/farcaster/$fid/links'
      fullPath: '/api/farcaster/$fid/links'
      preLoaderRoute: typeof ApiFarcasterFidLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/$fid/keys': {
      id: '/api/farcaster/$fid/keys'
      path: '/api/farcaster/$fid/keys'
      fullPath: '/api/farcaster/$fid/keys'
      preLoaderRoute: typeof ApiFarcasterFidKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/$fid/casts': {
      id: '/api/farcaster/$fid/casts'
      path: '/api/farcaster/$fid/casts'
      fullPath: '/api/farcaster/$fid/casts'
      preLoaderRoute: typeof ApiFarcasterFidCastsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  NotFoundRoute: NotFoundRoute,
  PingRoute: PingRoute,
  ShareCastRoute: ShareCastRoute,
  DotwellKnownFarcasterDotjsonRoute: DotwellKnownFarcasterDotjsonRoute,
  ApiEventsRoute: ApiEventsRoute,
  CastsHashRoute: CastsHashRoute,
  EventsIdRoute: EventsIdRoute,
  FidsFidRoute: FidsFidRoute,
  UsernamesUsernameRoute: UsernamesUsernameRoute,
  ApiFarcasterCastRoute: ApiFarcasterCastRoute,
  ApiFarcasterUserRoute: ApiFarcasterUserRoute,
  ApiNeynarCastRoute: ApiNeynarCastRoute,
  ApiNeynarUserRoute: ApiNeynarUserRoute,
  ApiSignersEnrichedRoute: ApiSignersEnrichedRoute,
  ApiSignersMessagesRoute: ApiSignersMessagesRoute,
  ApiSignersStatsRoute: ApiSignersStatsRoute,
  ApiSnapchainCastRoute: ApiSnapchainCastRoute,
  ApiSnapchainEventRoute: ApiSnapchainEventRoute,
  ApiSnapchainInfoRoute: ApiSnapchainInfoRoute,
  ApiFarcasterFidCastsRoute: ApiFarcasterFidCastsRoute,
  ApiFarcasterFidKeysRoute: ApiFarcasterFidKeysRoute,
  ApiFarcasterFidLinksRoute: ApiFarcasterFidLinksRoute,
  ApiFarcasterFidReactionsRoute: ApiFarcasterFidReactionsRoute,
  ApiFarcasterFidSignersRoute: ApiFarcasterFidSignersRoute,
  ApiFarcasterFidVerificationsRoute: ApiFarcasterFidVerificationsRoute,
  ApiFidFidStatsRoute: ApiFidFidStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
